apiVersion: v1
kind: Service
metadata:
  name: cst407net-service
  namespace: cst407-deployment
spec:
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 80  # Port the LoadBalancer will expose
      targetPort: 80 # Port the container is listening on
  selector:
    app: cst407