apiVersion: v1
kind: Service
metadata:
  labels:
    app: cst407net-service
    app.kubernetes.io/instance: cst407webpage
  name: cst407net-service
  namespace: cst407-deployment
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 31460
  selector:
    app: cst407
  sessionAffinity: None
  type: NodePort