apiVersion: v1
kind: Service
metadata:
  name: cst407net-service
  namespace: cst407-deployment
  labels:
    app: cst407net-service
spec:
  type: nodePort
  ports:
  - name: http
  #loadbalancer port
    port: 80
    protocol: TCP
    targetPort: 31460
    # this pod port 
  selector:
  # now we choose which pods to load balance
    app: cst407
  sessionAffinity: None