name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: |
        echo "${{ secrets.DOCKERPASSWORD }}" | docker login -u "intime333" --password-stdin
        docker build -t cool_docker .
        docker tag cool_docker intime333/nice_docker:latest
        docker push intime333/nice_docker:latest
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{secrets.KUBE_CONFIG}} | base64 --decode > ${HOME}/.kube/config
    - name: Use context
      run: |
        kubectl version
        kubectl config view
    - name: Tell k8s to restart the cluster
      run:  kubectl rollout restart deployment cst407-deployment
